// <auto-generated />
using System;
using BurgerKiosk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerKiosk.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505080601_AddMenuImageAndDescription")]
    partial class AddMenuImageAndDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BurgerKiosk.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "버거",
                            Description = "",
                            ImagePath = "",
                            IsAvailable = true,
                            Name = "불고기버거",
                            Price = 5000
                        },
                        new
                        {
                            Id = 2,
                            Category = "버거",
                            Description = "",
                            ImagePath = "",
                            IsAvailable = true,
                            Name = "치즈버거",
                            Price = 4500
                        },
                        new
                        {
                            Id = 3,
                            Category = "버거",
                            Description = "",
                            ImagePath = "",
                            IsAvailable = true,
                            Name = "새우버거",
                            Price = 4000
                        },
                        new
                        {
                            Id = 4,
                            Category = "음료",
                            Description = "",
                            ImagePath = "",
                            IsAvailable = true,
                            Name = "콜라",
                            Price = 2000
                        },
                        new
                        {
                            Id = 5,
                            Category = "음료",
                            Description = "",
                            ImagePath = "",
                            IsAvailable = true,
                            Name = "사이다",
                            Price = 2000
                        },
                        new
                        {
                            Id = 6,
                            Category = "사이드",
                            Description = "",
                            ImagePath = "",
                            IsAvailable = true,
                            Name = "감자튀김",
                            Price = 2500
                        },
                        new
                        {
                            Id = 7,
                            Category = "사이드",
                            Description = "",
                            ImagePath = "",
                            IsAvailable = true,
                            Name = "양파링",
                            Price = 2500
                        });
                });

            modelBuilder.Entity("BurgerKiosk.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BurgerKiosk.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MenuId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("BurgerKiosk.Models.OrderItem", b =>
                {
                    b.HasOne("BurgerKiosk.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BurgerKiosk.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BurgerKiosk.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
